spring:
  application:
     name: start
  datasource: 
    url : jdbc:oracle:thin:@192.168.130.17:1521:XE
    username : KH11_PJS
    password : KH1234
    driver-class-name: oracle.jdbc.driver.OracleDriver

server: 
  port: 80